# Generated by Django 2.0.2 on 2018-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0021_remove_uploadfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readsfile1', models.FileField(null=True, upload_to='')),
                ('readsfile2', models.FileField(null=True, upload_to='')),
                ('adapters', models.CharField(max_length=50, null=True)),
                ('key', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readsfile', models.FileField(default='/project/home17/whb17/public_html/randtestreads.fasta', upload_to='')),
                ('user_email', models.EmailField(default='whb17@ic.ac.uk', max_length=254)),
            ],
        ),
    ]
