# Generated by Django 2.0.2 on 2018-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0024_auto_20180220_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='adapter',
            field=models.CharField(default='ACGT', max_length=50, null=True),
        ),
    ]
