# Generated by Django 2.0.2 on 2018-02-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0025_uploadfile_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlejob',
            name='key',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
