# Generated by Django 2.0.2 on 2018-02-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0029_uploadfile_randkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetest',
            name='image',
        ),
        migrations.AddField(
            model_name='imagetest',
            name='name',
            field=models.CharField(default='Default Person', max_length=50),
        ),
        migrations.AddField(
            model_name='imagetest',
            name='user_email',
            field=models.EmailField(default='whb17@ic.ac.uk', max_length=254),
        ),
    ]
