# Generated by Django 2.0.2 on 2018-02-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('align', '0030_auto_20180223_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ent_key',
            new_name='EntKey',
        ),
    ]
